// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestoranDesktopApp.MigrationData;

#nullable disable

namespace RestoranDesktopApp.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20230106144954_s")]
    partial class s
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuyurtmalarMenu", b =>
                {
                    b.Property<int>("Btaomlarid")
                        .HasColumnType("integer");

                    b.Property<int>("Buyurtmalarsid")
                        .HasColumnType("integer");

                    b.HasKey("Btaomlarid", "Buyurtmalarsid");

                    b.HasIndex("Buyurtmalarsid");

                    b.ToTable("BuyurtmalarMenu");
                });

            modelBuilder.Entity("RestoranDesktopApp.Modules.Buyurtmalar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("usum")
                        .HasColumnType("integer");

                    b.Property<string>("vaqti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Buyurtmalar");
                });

            modelBuilder.Entity("RestoranDesktopApp.Modules.Menu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("TaomTuri")
                        .HasColumnType("integer");

                    b.Property<int>("narxi")
                        .HasColumnType("integer");

                    b.Property<string>("nomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("RestoranDesktopApp.Modules.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("RegistrationTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BuyurtmalarMenu", b =>
                {
                    b.HasOne("RestoranDesktopApp.Modules.Menu", null)
                        .WithMany()
                        .HasForeignKey("Btaomlarid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestoranDesktopApp.Modules.Buyurtmalar", null)
                        .WithMany()
                        .HasForeignKey("Buyurtmalarsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
