// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestoranDesktopApp.MigrationData;

#nullable disable

namespace RestoranDesktopApp.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20230107130653_d")]
    partial class d
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestoranDesktopApp.Modules.Buyurtmalar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Menuid")
                        .HasColumnType("integer");

                    b.Property<int>("usum")
                        .HasColumnType("integer");

                    b.Property<string>("vaqti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Menuid");

                    b.ToTable("Buyurtmalar");
                });

            modelBuilder.Entity("RestoranDesktopApp.Modules.Menu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("TaomTuri")
                        .HasColumnType("integer");

                    b.Property<int>("narxi")
                        .HasColumnType("integer");

                    b.Property<string>("nomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("RestoranDesktopApp.Modules.Taomlar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Buyurtmalarid")
                        .HasColumnType("integer");

                    b.Property<int>("narxi")
                        .HasColumnType("integer");

                    b.Property<string>("nomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Buyurtmalarid");

                    b.ToTable("Taomlar");
                });

            modelBuilder.Entity("RestoranDesktopApp.Modules.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("RegistrationTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RestoranDesktopApp.Modules.Buyurtmalar", b =>
                {
                    b.HasOne("RestoranDesktopApp.Modules.Menu", null)
                        .WithMany("Buyurtmalars")
                        .HasForeignKey("Menuid");
                });

            modelBuilder.Entity("RestoranDesktopApp.Modules.Taomlar", b =>
                {
                    b.HasOne("RestoranDesktopApp.Modules.Buyurtmalar", null)
                        .WithMany("Btaomlar")
                        .HasForeignKey("Buyurtmalarid");
                });

            modelBuilder.Entity("RestoranDesktopApp.Modules.Buyurtmalar", b =>
                {
                    b.Navigation("Btaomlar");
                });

            modelBuilder.Entity("RestoranDesktopApp.Modules.Menu", b =>
                {
                    b.Navigation("Buyurtmalars");
                });
#pragma warning restore 612, 618
        }
    }
}
